language: swift
osx_image: xcode11

addons:
  homebrew:
    packages:
    - xcodegen

before_install:
  - make

script:
  - set -o pipefail && xcodebuild -project TinyEMU-iOS.xcodeproj -scheme TinyEMU-iOS -sdk iphonesimulator build | xcpretty
