name: TinyEMU-iOS

packages:
  SwiftTerm:
    path: Vendors/SwiftTerm

options:
  bundleIdPrefix: com.fernandotcl
  deploymentTarget:
    iOS: 13.5
  usesTabs: false
  identWidth: 4
  tabWidth: 4

settings:
  DEVELOPMENT_TEAM: LF9WRPC84S
  SWIFT_VERSION: 5.2

targets:

  TinyEMU-iOS:
    type: application
    platform: iOS
    info:
      path: Info.plist
      properties:
        UILaunchStoryboardName: Launch
        UISupportedInterfaceOrientations: [
          UIInterfaceOrientationPortrait,
          UIInterfaceOrientationLandscapeLeft,
          UIInterfaceOrientationLandscapeRight,
        ]
        UISupportedInterfaceOrientations~ipad: [
          UIInterfaceOrientationPortrait,
          UIInterfaceOrientationLandscapeLeft,
          UIInterfaceOrientationLandscapeRight,
          UIInterfaceOrientationPortraitUpsideDown
        ]
        UIFileSharingEnabled: true
        LSSupportsOpeningDocumentsInPlace: true

    settings:
      SWIFT_OBJC_BRIDGING_HEADER: Sources/BridgingHeader.h
      OTHER_LDFLAGS: -lresolv -lz
    sources:
      - Sources
      - Launch.storyboard
      - Assets/Machine.bundle
    dependencies:
      - target: TinyEMU
      - package: SwiftTerm

  TinyEMU:
    productName: libTinyEMU
    type: library.static
    platform: iOS
    postCompileScripts:
      - inputFiles:
        - $(SRCROOT)/**/*.{c,h}
        - $(SRCROOT)/Makefile
        outputFiles:
          - $(BUILT_PRODUCTS_DIR)/libtemu.a
        script: |
                set -e
                cd "${SRCROOT}"/Vendors/TinyEMU
                make clean
                if test "x${PLATFORM_NAME}" = xiphoneos; then
                  make CONFIG_IOS=y CONFIG_FS_NET= CONFIG_SDL= CONFIG_X86EMU=
                else
                  make CONFIG_IOS_SIMULATOR=y CONFIG_FS_NET= CONFIG_SDL= CONFIG_X86EMU=
                fi
                mkdir -p "${BUILT_PRODUCTS_DIR}"/
                mv libtemu.a "${BUILT_PRODUCTS_DIR}/libTinyEMU.a"
                make clean
    requiresObjCLinking: true
