name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-10.15
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: brew install xcodegen
      - run: make
      - run: set -o pipefail && xcodebuild -project TinyEMU-iOS.xcodeproj -scheme TinyEMU-iOS -sdk iphonesimulator build | xcpretty
